import pygame

# Khởi tạo Pygame
pygame.init()

# Lấy kích thước màn hình máy tính
screen_info = pygame.display.Info()
screen_width = screen_info.current_w
screen_height = screen_info.current_h

MAIN_WIDTH = int(screen_height * 0.9)
WIDTH = MAIN_WIDTH
HEIGHT = int(screen_height * 0.9)
# Background
WIDTH_BG = int(screen_width * 0.8)
HEIGHT_BG = int(screen_height * 0.9)



# COLORS
EASY_BG_COLOR = (193, 212, 215)
MEDIUM_BG_COLOR = (188, 244, 231)
HARD_BG_COLOR = (251, 200, 220)
	
LINE_COLOR = (255, 255, 255)
CIRCLE_COLOR = (255, 255, 255)
CROSS_COLOR = (0, 0, 0)
WIN_LINE_COLOR = (0, 255, 255)
EASY_GAME_BG_COLOR = (3, 122, 144)
MEDIUM_GAME_BG_COLOR = (1, 255, 195)
HARD_GAME_BG_COLOR = (255, 32, 121)


MAP_HOVER_COLOR = (41, 233, 30)
GAMEMODE_HOVER_COLOR = (218, 0, 255)
LEVEL_HOVER_COLOR = (0, 222, 255)
RnQ_HOVER_COLOR = (233, 30, 99)

MAP_SELECTED_COLOR = (41, 233, 30)
GAMEMODE_SELECTED_COLOR = (218, 0, 255)
LEVEL_SELECTED_COLOR = (0, 222, 255)
LEVEL_DISABLED_COLOR = (222, 222, 222)

WHITE = (255, 255, 255)
GRAY = (150, 150, 150)
BLACK = (0, 0, 0)

# TEXT COLOR
TEXT_COLOR = (255, 255, 255)
FONT_SIZE = 36

# 60% - gamemode
# 30% reset + quit
# 10% map
# Button
MAP_BUTTON_WIDTH = int(0.7*(WIDTH_BG - WIDTH))//5
MAP_BUTTON_HEIGHT = 30
MAP_BUTTON_MARGIN = int(0.3*(WIDTH_BG - WIDTH))//5

LEVEL_BUTTON_WIDTH = (WIDTH_BG - WIDTH)//3
LEVEL_BUTTON_HEIGHT = int(HEIGHT_BG*0.07)

GAMEMODE_BUTTON_WIDTH = int(0.6*(WIDTH_BG - WIDTH))
GAMEMODE_BUTTON_HEIGHT = int(0.1*HEIGHT_BG)

RESET_BUTTON_WIDTH = int(0.7*(WIDTH_BG - WIDTH))
RESET_BUTTON_HEIGHT = int(0.1*HEIGHT_BG)

# Center align - right
X_LEVEL_RIGHT_CENTER = WIDTH + (WIDTH_BG - WIDTH - LEVEL_BUTTON_WIDTH) // 2
X_GAMEMODE_RIGHT_CENTER = WIDTH + (WIDTH_BG - WIDTH - GAMEMODE_BUTTON_WIDTH) // 2
X_RESET_RIGHT_CENTER = WIDTH + (WIDTH_BG - WIDTH - RESET_BUTTON_WIDTH) // 2

X_MAP_BUTTON = WIDTH + MAP_BUTTON_MARGIN//2
Y_MAP_BUTTON = 44
Y_GAMEMODE_BUTTON = Y_MAP_BUTTON + MAP_BUTTON_HEIGHT + 60
Y_LEVEL_BUTTON = Y_GAMEMODE_BUTTON + (GAMEMODE_BUTTON_HEIGHT + 20)*2
Y_RESET_BUTTON = Y_LEVEL_BUTTON + (LEVEL_BUTTON_HEIGHT + 20)*3